ksniff graceful shutdown on Ctrl+C + Wireshark doesn't close on exit
eldadru/ksniff pull request #66
Opened 2020-03-21 08:14 UTC by aviramha

Thanks for the awesome plugin Eldad!
One annoying UX I had is if I close ksniff because I had enough traffic it also closes Wireshark.
I changed the flow so that Wireshark stays open and needed to add handling of Ctrl+C so it'll be a valid exit scenario.
This seems to fix a bug on capturing to a file, whereas I couldn't find a way to exit in a nice manner.

It's my first Go coding so feel free to fire away.

2020-03-31 17:04 UTC, aviramha commented
@eldadru Bump

2020-03-31 17:13 UTC, eldadru commented
Hi @aviramha - sorry for the delay, had a rough time..

I'll review your code today, thank you so much for this contribution!

2020-03-31 17:15 UTC, eldadru commented on pkg/cmd/sniff.go
>  	defer func() {
Call defer directly
`defer o.Cleanup()`

2020-03-31 17:24 UTC, eldadru commented on pkg/cmd/sniff.go
> +
remove this new line

2020-03-31 17:25 UTC, eldadru commented on pkg/cmd/sniff.go
> +		os.Exit(0)
Add a log line specifying ksniff cleaned everything is about to exit

2020-03-31 17:25 UTC, eldadru requested changes
See my comments

2020-03-31 20:10 UTC, aviramha commented
Done! Check it out :)

2020-03-31 20:29 UTC, eldadru commented
Thanks, did you push the new code? I don't see new commits

2020-03-31 20:42 UTC, eldadru approved these changes

2020-03-31 20:48 UTC, eldadru commented
It seems the windows build is broken

`pkg/cmd/sniff.go:356:4: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
pkg/cmd/sniff.go:357:4: unknown field 'Pgid' in struct literal of type syscall.SysProcAttr
Makefile:26: recipe for target 'windows' failed
make: *** [windows] Error 2
The command "make all" exited with 2.`

2020-04-01 05:55 UTC, aviramha commented
Should I create a _linux and _windows file for the specific procedure? (not sure what's the go approach here)

2020-05-09 09:01 UTC, eldadru commented
Hi @aviramha, sorry again for the late response...

In this case, I believe the cleaner approach is to extract the process execution code to its own struct and hide the "specific os code" there, the struct will expose a single call to execute the Wireshark command.

WDYT?

2020-05-10 06:44 UTC, aviramha commented
Sounds good, from what I understand specific OS code can be seperated only by files, so I assume that we'll have windows file and unix file?

2020-09-30 16:44 UTC, Slach commented
@aviramha any news about this PR?

2020-09-30 17:37 UTC, aviramha commented
> @aviramha any news about this PR?

I don't think I'll get to it soon. Feel free to continue where I left it :)

2021-01-21 05:33 UTC, aviramha commented
I don't think so

2021-03-12 01:33 UTC, pnovotnak commented
I can take this over, I spend a few mins each day killing off tcpdump binaries (let alone the ones I forget) so I may as well just spend an hour up front.

> In this case, I believe the cleaner approach is to extract the process execution code to its own struct and hide the "specific os code" there, the struct will expose a single call to execute the Wireshark command.

@bostrt you're saying the contents of the (o *Ksniff) Run() function ought to be hidden in a struct, yea?

2026-02-17 16:19 UTC, closed without merging